version: "3.9"

services:
  app:
    build: .
    container_name: 'app-container'
    command: make run-prod
    env_file:
      - .env
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres-container'
    image: postgres
    restart: always
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
